import { CountryCode } from 'libphonenumber-js';

export const countries = [
  { code: "93", flag: "🇦🇫", name: "Afghanistan", countryCode: "AF" as CountryCode },
  { code: "355", flag: "🇦🇱", name: "Albania", countryCode: "AL" as CountryCode },
  { code: "213", flag: "🇩🇿", name: "Algeria", countryCode: "DZ" as CountryCode },
  { code: "1684", flag: "🇦🇸", name: "American Samoa", countryCode: "AS" as CountryCode },
  { code: "376", flag: "🇦🇩", name: "Andorra", countryCode: "AD" as CountryCode },
  { code: "244", flag: "🇦🇴", name: "Angola", countryCode: "AO" as CountryCode },
  { code: "1264", flag: "🇦🇮", name: "Anguilla", countryCode: "AI" as CountryCode },
  { code: "1268", flag: "🇦🇬", name: "Antigua and Barbuda", countryCode: "AG" as CountryCode },
  { code: "54", flag: "🇦🇷", name: "Argentina", countryCode: "AR" as CountryCode },
  { code: "374", flag: "🇦🇲", name: "Armenia", countryCode: "AM" as CountryCode },
  { code: "297", flag: "🇦🇼", name: "Aruba", countryCode: "AW" as CountryCode },
  { code: "61", flag: "🇦🇺", name: "Australia", countryCode: "AU" as CountryCode },
  { code: "43", flag: "🇦🇹", name: "Austria", countryCode: "AT" as CountryCode },
  { code: "994", flag: "🇦🇿", name: "Azerbaijan", countryCode: "AZ" as CountryCode },
  { code: "1242", flag: "🇧🇸", name: "Bahamas", countryCode: "BS" as CountryCode },
  { code: "973", flag: "🇧🇭", name: "Bahrain", countryCode: "BH" as CountryCode },
  { code: "880", flag: "🇧🇩", name: "Bangladesh", countryCode: "BD" as CountryCode },
  { code: "1246", flag: "🇧🇧", name: "Barbados", countryCode: "BB" as CountryCode },
  { code: "375", flag: "🇧🇾", name: "Belarus", countryCode: "BY" as CountryCode },
  { code: "32", flag: "🇧🇪", name: "Belgium", countryCode: "BE" as CountryCode },
  { code: "501", flag: "🇧🇿", name: "Belize", countryCode: "BZ" as CountryCode },
  { code: "229", flag: "🇧🇯", name: "Benin", countryCode: "BJ" as CountryCode },
  { code: "1441", flag: "🇧🇲", name: "Bermuda", countryCode: "BM" as CountryCode },
  { code: "975", flag: "🇧🇹", name: "Bhutan", countryCode: "BT" as CountryCode },
  { code: "591", flag: "🇧🇴", name: "Bolivia", countryCode: "BO" as CountryCode },
  { code: "387", flag: "🇧🇦", name: "Bosnia and Herzegovina", countryCode: "BA" as CountryCode },
  { code: "267", flag: "🇧🇼", name: "Botswana", countryCode: "BW" as CountryCode },
  { code: "55", flag: "🇧🇷", name: "Brazil", countryCode: "BR" as CountryCode },
  { code: "673", flag: "🇧🇳", name: "Brunei", countryCode: "BN" as CountryCode },
  { code: "359", flag: "🇧🇬", name: "Bulgaria", countryCode: "BG" as CountryCode },
  { code: "226", flag: "🇧🇫", name: "Burkina Faso", countryCode: "BF" as CountryCode },
  { code: "257", flag: "🇧🇮", name: "Burundi", countryCode: "BI" as CountryCode },
  { code: "855", flag: "🇰🇭", name: "Cambodia", countryCode: "KH" as CountryCode },
  { code: "237", flag: "🇨🇲", name: "Cameroon", countryCode: "CM" as CountryCode },
  { code: "1", flag: "🇨🇦", name: "Canada", countryCode: "CA" as CountryCode },
  { code: "238", flag: "🇨🇻", name: "Cape Verde", countryCode: "CV" as CountryCode },
  { code: "1345", flag: "🇰🇾", name: "Cayman Islands", countryCode: "KY" as CountryCode },
  { code: "236", flag: "🇨🇫", name: "Central African Republic", countryCode: "CF" as CountryCode },
  { code: "235", flag: "🇹🇩", name: "Chad", countryCode: "TD" as CountryCode },
  { code: "56", flag: "🇨🇱", name: "Chile", countryCode: "CL" as CountryCode },
  { code: "86", flag: "🇨🇳", name: "China", countryCode: "CN" as CountryCode },
  { code: "57", flag: "🇨🇴", name: "Colombia", countryCode: "CO" as CountryCode },
  { code: "269", flag: "🇰🇲", name: "Comoros", countryCode: "KM" as CountryCode },
  { code: "242", flag: "🇨🇬", name: "Congo", countryCode: "CG" as CountryCode },
  { code: "243", flag: "🇨🇩", name: "Congo (DRC)", countryCode: "CD" as CountryCode },
  { code: "682", flag: "🇨🇰", name: "Cook Islands", countryCode: "CK" as CountryCode },
  { code: "506", flag: "🇨🇷", name: "Costa Rica", countryCode: "CR" as CountryCode },
  { code: "385", flag: "🇭🇷", name: "Croatia", countryCode: "HR" as CountryCode },
  { code: "53", flag: "🇨🇺", name: "Cuba", countryCode: "CU" as CountryCode },
  { code: "357", flag: "🇨🇾", name: "Cyprus", countryCode: "CY" as CountryCode },
  { code: "420", flag: "🇨🇿", name: "Czech Republic", countryCode: "CZ" as CountryCode },
  { code: "45", flag: "🇩🇰", name: "Denmark", countryCode: "DK" as CountryCode },
  { code: "253", flag: "🇩🇯", name: "Djibouti", countryCode: "DJ" as CountryCode },
  { code: "1767", flag: "🇩🇲", name: "Dominica", countryCode: "DM" as CountryCode },
  { code: "1809", flag: "🇩🇴", name: "Dominican Republic", countryCode: "DO" as CountryCode },
  { code: "593", flag: "🇪🇨", name: "Ecuador", countryCode: "EC" as CountryCode },
  { code: "20", flag: "🇪🇬", name: "Egypt", countryCode: "EG" as CountryCode },
  { code: "503", flag: "🇸🇻", name: "El Salvador", countryCode: "SV" as CountryCode },
  { code: "240", flag: "🇬🇶", name: "Equatorial Guinea", countryCode: "GQ" as CountryCode },
  { code: "291", flag: "🇪🇷", name: "Eritrea", countryCode: "ER" as CountryCode },
  { code: "372", flag: "🇪🇪", name: "Estonia", countryCode: "EE" as CountryCode },
  { code: "251", flag: "🇪🇹", name: "Ethiopia", countryCode: "ET" as CountryCode },
  { code: "500", flag: "🇫🇰", name: "Falkland Islands", countryCode: "FK" as CountryCode },
  { code: "298", flag: "🇫🇴", name: "Faroe Islands", countryCode: "FO" as CountryCode },
  { code: "679", flag: "🇫🇯", name: "Fiji", countryCode: "FJ" as CountryCode },
  { code: "358", flag: "🇫🇮", name: "Finland", countryCode: "FI" as CountryCode },
  { code: "33", flag: "🇫🇷", name: "France", countryCode: "FR" as CountryCode },
  { code: "594", flag: "🇬🇫", name: "French Guiana", countryCode: "GF" as CountryCode },
  { code: "689", flag: "🇵🇫", name: "French Polynesia", countryCode: "PF" as CountryCode },
  { code: "241", flag: "🇬🇦", name: "Gabon", countryCode: "GA" as CountryCode },
  { code: "220", flag: "🇬🇲", name: "Gambia", countryCode: "GM" as CountryCode },
  { code: "995", flag: "🇬🇪", name: "Georgia", countryCode: "GE" as CountryCode },
  { code: "49", flag: "🇩🇪", name: "Germany", countryCode: "DE" as CountryCode },
  { code: "233", flag: "🇬🇭", name: "Ghana", countryCode: "GH" as CountryCode },
  { code: "350", flag: "🇬🇮", name: "Gibraltar", countryCode: "GI" as CountryCode },
  { code: "30", flag: "🇬🇷", name: "Greece", countryCode: "GR" as CountryCode },
  { code: "299", flag: "🇬🇱", name: "Greenland", countryCode: "GL" as CountryCode },
  { code: "1473", flag: "🇬🇩", name: "Grenada", countryCode: "GD" as CountryCode },
  { code: "590", flag: "🇬🇵", name: "Guadeloupe", countryCode: "GP" as CountryCode },
  { code: "1671", flag: "🇬🇺", name: "Guam", countryCode: "GU" as CountryCode },
  { code: "502", flag: "🇬🇹", name: "Guatemala", countryCode: "GT" as CountryCode },
  { code: "224", flag: "🇬🇳", name: "Guinea", countryCode: "GN" as CountryCode },
  { code: "245", flag: "🇬🇼", name: "Guinea-Bissau", countryCode: "GW" as CountryCode },
  { code: "592", flag: "🇬🇾", name: "Guyana", countryCode: "GY" as CountryCode },
  { code: "509", flag: "🇭🇹", name: "Haiti", countryCode: "HT" as CountryCode },
  { code: "504", flag: "🇭🇳", name: "Honduras", countryCode: "HN" as CountryCode },
  { code: "852", flag: "🇭🇰", name: "Hong Kong", countryCode: "HK" as CountryCode },
  { code: "36", flag: "🇭🇺", name: "Hungary", countryCode: "HU" as CountryCode },
  { code: "354", flag: "🇮🇸", name: "Iceland", countryCode: "IS" as CountryCode },
  { code: "91", flag: "🇮🇳", name: "India", countryCode: "IN" as CountryCode },
  { code: "62", flag: "🇮🇩", name: "Indonesia", countryCode: "ID" as CountryCode },
  { code: "98", flag: "🇮🇷", name: "Iran", countryCode: "IR" as CountryCode },
  { code: "964", flag: "🇮🇶", name: "Iraq", countryCode: "IQ" as CountryCode },
  { code: "353", flag: "🇮🇪", name: "Ireland", countryCode: "IE" as CountryCode },
  { code: "972", flag: "🇮🇱", name: "Israel", countryCode: "IL" as CountryCode },
  { code: "39", flag: "🇮🇹", name: "Italy", countryCode: "IT" as CountryCode },
  { code: "225", flag: "🇨🇮", name: "Ivory Coast", countryCode: "CI" as CountryCode },
  { code: "1876", flag: "🇯🇲", name: "Jamaica", countryCode: "JM" as CountryCode },
  { code: "81", flag: "🇯🇵", name: "Japan", countryCode: "JP" as CountryCode },
  { code: "962", flag: "🇯🇴", name: "Jordan", countryCode: "JO" as CountryCode },
  { code: "7", flag: "🇰🇿", name: "Kazakhstan", countryCode: "KZ" as CountryCode },
  { code: "254", flag: "🇰🇪", name: "Kenya", countryCode: "KE" as CountryCode },
  { code: "686", flag: "🇰🇮", name: "Kiribati", countryCode: "KI" as CountryCode },
  { code: "383", flag: "🇽🇰", name: "Kosovo", countryCode: "XK" as CountryCode },
  { code: "965", flag: "🇰🇼", name: "Kuwait", countryCode: "KW" as CountryCode },
  { code: "996", flag: "🇰🇬", name: "Kyrgyzstan", countryCode: "KG" as CountryCode },
  { code: "856", flag: "🇱🇦", name: "Laos", countryCode: "LA" as CountryCode },
  { code: "371", flag: "🇱🇻", name: "Latvia", countryCode: "LV" as CountryCode },
  { code: "961", flag: "🇱🇧", name: "Lebanon", countryCode: "LB" as CountryCode },
  { code: "266", flag: "🇱🇸", name: "Lesotho", countryCode: "LS" as CountryCode },
  { code: "231", flag: "🇱🇷", name: "Liberia", countryCode: "LR" as CountryCode },
  { code: "218", flag: "🇱🇾", name: "Libya", countryCode: "LY" as CountryCode },
  { code: "423", flag: "🇱🇮", name: "Liechtenstein", countryCode: "LI" as CountryCode },
  { code: "370", flag: "🇱🇹", name: "Lithuania", countryCode: "LT" as CountryCode },
  { code: "352", flag: "🇱🇺", name: "Luxembourg", countryCode: "LU" as CountryCode },
  { code: "853", flag: "🇲🇴", name: "Macau", countryCode: "MO" as CountryCode },
  { code: "389", flag: "🇲🇰", name: "Macedonia", countryCode: "MK" as CountryCode },
  { code: "261", flag: "🇲🇬", name: "Madagascar", countryCode: "MG" as CountryCode },
  { code: "265", flag: "🇲🇼", name: "Malawi", countryCode: "MW" as CountryCode },
  { code: "60", flag: "🇲🇾", name: "Malaysia", countryCode: "MY" as CountryCode },
  { code: "960", flag: "🇲🇻", name: "Maldives", countryCode: "MV" as CountryCode },
  { code: "223", flag: "🇲🇱", name: "Mali", countryCode: "ML" as CountryCode },
  { code: "356", flag: "🇲🇹", name: "Malta", countryCode: "MT" as CountryCode },
  { code: "692", flag: "🇲🇭", name: "Marshall Islands", countryCode: "MH" as CountryCode },
  { code: "596", flag: "🇲🇶", name: "Martinique", countryCode: "MQ" as CountryCode },
  { code: "222", flag: "🇲🇷", name: "Mauritania", countryCode: "MR" as CountryCode },
  { code: "230", flag: "🇲🇺", name: "Mauritius", countryCode: "MU" as CountryCode },
  { code: "262", flag: "🇾🇹", name: "Mayotte", countryCode: "YT" as CountryCode },
  { code: "52", flag: "🇲🇽", name: "Mexico", countryCode: "MX" as CountryCode },
  { code: "691", flag: "🇫🇲", name: "Micronesia", countryCode: "FM" as CountryCode },
  { code: "373", flag: "🇲🇩", name: "Moldova", countryCode: "MD" as CountryCode },
  { code: "377", flag: "🇲🇨", name: "Monaco", countryCode: "MC" as CountryCode },
  { code: "976", flag: "🇲🇳", name: "Mongolia", countryCode: "MN" as CountryCode },
  { code: "382", flag: "🇲🇪", name: "Montenegro", countryCode: "ME" as CountryCode },
  { code: "1664", flag: "🇲🇸", name: "Montserrat", countryCode: "MS" as CountryCode },
  { code: "212", flag: "🇲🇦", name: "Morocco", countryCode: "MA" as CountryCode },
  { code: "258", flag: "🇲🇿", name: "Mozambique", countryCode: "MZ" as CountryCode },
  { code: "95", flag: "🇲🇲", name: "Myanmar", countryCode: "MM" as CountryCode },
  { code: "264", flag: "🇳🇦", name: "Namibia", countryCode: "NA" as CountryCode },
  { code: "674", flag: "🇳🇷", name: "Nauru", countryCode: "NR" as CountryCode },
  { code: "977", flag: "🇳🇵", name: "Nepal", countryCode: "NP" as CountryCode },
  { code: "31", flag: "🇳🇱", name: "Netherlands", countryCode: "NL" as CountryCode },
  { code: "687", flag: "🇳🇨", name: "New Caledonia", countryCode: "NC" as CountryCode },
  { code: "64", flag: "🇳🇿", name: "New Zealand", countryCode: "NZ" as CountryCode },
  { code: "505", flag: "🇳🇮", name: "Nicaragua", countryCode: "NI" as CountryCode },
  { code: "227", flag: "🇳🇪", name: "Niger", countryCode: "NE" as CountryCode },
  { code: "234", flag: "🇳🇬", name: "Nigeria", countryCode: "NG" as CountryCode },
  { code: "683", flag: "🇳🇺", name: "Niue", countryCode: "NU" as CountryCode },
  { code: "850", flag: "🇰🇵", name: "North Korea", countryCode: "KP" as CountryCode },
  { code: "47", flag: "🇳🇴", name: "Norway", countryCode: "NO" as CountryCode },
  { code: "968", flag: "🇴🇲", name: "Oman", countryCode: "OM" as CountryCode },
  { code: "92", flag: "🇵🇰", name: "Pakistan", countryCode: "PK" as CountryCode },
  { code: "680", flag: "🇵🇼", name: "Palau", countryCode: "PW" as CountryCode },
  { code: "970", flag: "🇵🇸", name: "Palestine", countryCode: "PS" as CountryCode },
  { code: "507", flag: "🇵🇦", name: "Panama", countryCode: "PA" as CountryCode },
  { code: "675", flag: "🇵🇬", name: "Papua New Guinea", countryCode: "PG" as CountryCode },
  { code: "595", flag: "🇵🇾", name: "Paraguay", countryCode: "PY" as CountryCode },
  { code: "51", flag: "🇵🇪", name: "Peru", countryCode: "PE" as CountryCode },
  { code: "63", flag: "🇵🇭", name: "Philippines", countryCode: "PH" as CountryCode },
  { code: "48", flag: "🇵🇱", name: "Poland", countryCode: "PL" as CountryCode },
  { code: "351", flag: "🇵🇹", name: "Portugal", countryCode: "PT" as CountryCode },
  { code: "1787", flag: "🇵🇷", name: "Puerto Rico", countryCode: "PR" as CountryCode },
  { code: "974", flag: "🇶🇦", name: "Qatar", countryCode: "QA" as CountryCode },
  { code: "262", flag: "🇷🇪", name: "Réunion", countryCode: "RE" as CountryCode },
  { code: "40", flag: "🇷🇴", name: "Romania", countryCode: "RO" as CountryCode },
  { code: "7", flag: "🇷🇺", name: "Russia", countryCode: "RU" as CountryCode },
  { code: "250", flag: "🇷🇼", name: "Rwanda", countryCode: "RW" as CountryCode },
  { code: "290", flag: "🇸🇭", name: "Saint Helena", countryCode: "SH" as CountryCode },
  { code: "1869", flag: "🇰🇳", name: "Saint Kitts and Nevis", countryCode: "KN" as CountryCode },
  { code: "1758", flag: "🇱🇨", name: "Saint Lucia", countryCode: "LC" as CountryCode },
  { code: "508", flag: "🇵🇲", name: "Saint Pierre and Miquelon", countryCode: "PM" as CountryCode },
  { code: "1784", flag: "🇻🇨", name: "Saint Vincent and the Grenadines", countryCode: "VC" as CountryCode },
  { code: "685", flag: "🇼🇸", name: "Samoa", countryCode: "WS" as CountryCode },
  { code: "378", flag: "🇸🇲", name: "San Marino", countryCode: "SM" as CountryCode },
  { code: "239", flag: "🇸🇹", name: "São Tomé and Príncipe", countryCode: "ST" as CountryCode },
  { code: "966", flag: "🇸🇦", name: "Saudi Arabia", countryCode: "SA" as CountryCode },
  { code: "221", flag: "🇸🇳", name: "Senegal", countryCode: "SN" as CountryCode },
  { code: "381", flag: "🇷🇸", name: "Serbia", countryCode: "RS" as CountryCode },
  { code: "248", flag: "🇸🇨", name: "Seychelles", countryCode: "SC" as CountryCode },
  { code: "232", flag: "🇸🇱", name: "Sierra Leone", countryCode: "SL" as CountryCode },
  { code: "65", flag: "🇸🇬", name: "Singapore", countryCode: "SG" as CountryCode },
  { code: "421", flag: "🇸🇰", name: "Slovakia", countryCode: "SK" as CountryCode },
  { code: "386", flag: "🇸🇮", name: "Slovenia", countryCode: "SI" as CountryCode },
  { code: "677", flag: "🇸🇧", name: "Solomon Islands", countryCode: "SB" as CountryCode },
  { code: "252", flag: "🇸🇴", name: "Somalia", countryCode: "SO" as CountryCode },
  { code: "27", flag: "🇿🇦", name: "South Africa", countryCode: "ZA" as CountryCode },
  { code: "82", flag: "🇰🇷", name: "South Korea", countryCode: "KR" as CountryCode },
  { code: "211", flag: "🇸🇸", name: "South Sudan", countryCode: "SS" as CountryCode },
  { code: "34", flag: "🇪🇸", name: "Spain", countryCode: "ES" as CountryCode },
  { code: "94", flag: "🇱🇰", name: "Sri Lanka", countryCode: "LK" as CountryCode },
  { code: "249", flag: "🇸🇩", name: "Sudan", countryCode: "SD" as CountryCode },
  { code: "597", flag: "🇸🇷", name: "Suriname", countryCode: "SR" as CountryCode },
  { code: "268", flag: "🇸🇿", name: "Eswatini", countryCode: "SZ" as CountryCode },
  { code: "46", flag: "🇸🇪", name: "Sweden", countryCode: "SE" as CountryCode },
  { code: "41", flag: "🇨🇭", name: "Switzerland", countryCode: "CH" as CountryCode },
  { code: "963", flag: "🇸🇾", name: "Syria", countryCode: "SY" as CountryCode },
  { code: "886", flag: "🇹🇼", name: "Taiwan", countryCode: "TW" as CountryCode },
  { code: "992", flag: "🇹🇯", name: "Tajikistan", countryCode: "TJ" as CountryCode },
  { code: "255", flag: "🇹🇿", name: "Tanzania", countryCode: "TZ" as CountryCode },
  { code: "66", flag: "🇹🇭", name: "Thailand", countryCode: "TH" as CountryCode },
  { code: "670", flag: "🇹🇱", name: "Timor-Leste", countryCode: "TL" as CountryCode },
  { code: "228", flag: "🇹🇬", name: "Togo", countryCode: "TG" as CountryCode },
  { code: "690", flag: "🇹🇰", name: "Tokelau", countryCode: "TK" as CountryCode },
  { code: "676", flag: "🇹🇴", name: "Tonga", countryCode: "TO" as CountryCode },
  { code: "1868", flag: "🇹🇹", name: "Trinidad and Tobago", countryCode: "TT" as CountryCode },
  { code: "216", flag: "🇹🇳", name: "Tunisia", countryCode: "TN" as CountryCode },
  { code: "90", flag: "🇹🇷", name: "Turkey", countryCode: "TR" as CountryCode },
  { code: "993", flag: "🇹🇲", name: "Turkmenistan", countryCode: "TM" as CountryCode },
  { code: "1649", flag: "🇹🇨", name: "Turks and Caicos Islands", countryCode: "TC" as CountryCode },
  { code: "688", flag: "🇹🇻", name: "Tuvalu", countryCode: "TV" as CountryCode },
  { code: "256", flag: "🇺🇬", name: "Uganda", countryCode: "UG" as CountryCode },
  { code: "380", flag: "🇺🇦", name: "Ukraine", countryCode: "UA" as CountryCode },
  { code: "971", flag: "🇦🇪", name: "United Arab Emirates", countryCode: "AE" as CountryCode },
  { code: "44", flag: "🇬🇧", name: "United Kingdom", countryCode: "GB" as CountryCode },
  { code: "1", flag: "🇺🇸", name: "United States", countryCode: "US" as CountryCode },
  { code: "598", flag: "🇺🇾", name: "Uruguay", countryCode: "UY" as CountryCode },
  { code: "998", flag: "🇺🇿", name: "Uzbekistan", countryCode: "UZ" as CountryCode },
  { code: "678", flag: "🇻🇺", name: "Vanuatu", countryCode: "VU" as CountryCode },
  { code: "379", flag: "🇻🇦", name: "Vatican City", countryCode: "VA" as CountryCode },
  { code: "58", flag: "🇻🇪", name: "Venezuela", countryCode: "VE" as CountryCode },
  { code: "84", flag: "🇻🇳", name: "Vietnam", countryCode: "VN" as CountryCode },
  { code: "1284", flag: "🇻🇬", name: "British Virgin Islands", countryCode: "VG" as CountryCode },
  { code: "1340", flag: "🇻🇮", name: "US Virgin Islands", countryCode: "VI" as CountryCode },
  { code: "681", flag: "🇼🇫", name: "Wallis and Futuna", countryCode: "WF" as CountryCode },
  { code: "967", flag: "🇾🇪", name: "Yemen", countryCode: "YE" as CountryCode },
  { code: "260", flag: "🇿🇲", name: "Zambia", countryCode: "ZM" as CountryCode },
  { code: "263", flag: "🇿🇼", name: "Zimbabwe", countryCode: "ZW" as CountryCode },
];
