// Mock address data for Spain (simulating Google Places API)

export interface MockAddress {
  id: string;
  streetName: string;
  streetNumber?: string;
  neighborhood: string;
  city: string;
  postalCode: string;
  province: string;
  country: string;
  latitude: number;
  longitude: number;
  formattedAddress: string;
}

export const mockSpainAddresses: MockAddress[] = [
  // Madrid addresses
  {
    id: 'addr-1',
    streetName: 'Calle de Serrano',
    streetNumber: '45',
    neighborhood: 'Salamanca',
    city: 'Madrid',
    postalCode: '28001',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4290,
    longitude: -3.6850,
    formattedAddress: 'Calle de Serrano, 45, 28001 Madrid',
  },
  {
    id: 'addr-2',
    streetName: 'Calle de Alcalá',
    streetNumber: '120',
    neighborhood: 'Retiro',
    city: 'Madrid',
    postalCode: '28009',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4230,
    longitude: -3.6700,
    formattedAddress: 'Calle de Alcalá, 120, 28009 Madrid',
  },
  {
    id: 'addr-3',
    streetName: 'Gran Vía',
    streetNumber: '32',
    neighborhood: 'Centro',
    city: 'Madrid',
    postalCode: '28013',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4200,
    longitude: -3.7050,
    formattedAddress: 'Gran Vía, 32, 28013 Madrid',
  },
  {
    id: 'addr-4',
    streetName: 'Paseo de la Castellana',
    neighborhood: 'Chamartín',
    city: 'Madrid',
    postalCode: '28046',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4600,
    longitude: -3.6900,
    formattedAddress: 'Paseo de la Castellana, 28046 Madrid',
  },
  {
    id: 'addr-5',
    streetName: 'Calle de Velázquez',
    streetNumber: '78',
    neighborhood: 'Salamanca',
    city: 'Madrid',
    postalCode: '28006',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4320,
    longitude: -3.6780,
    formattedAddress: 'Calle de Velázquez, 78, 28006 Madrid',
  },
  // Additional "Se" addresses for testing
  {
    id: 'addr-se-1',
    streetName: 'Calle de Segovia',
    streetNumber: '12',
    neighborhood: 'La Latina',
    city: 'Madrid',
    postalCode: '28005',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4150,
    longitude: -3.7130,
    formattedAddress: 'Calle de Segovia, 12, 28005 Madrid',
  },
  {
    id: 'addr-se-2',
    streetName: 'Calle de Sevilla',
    streetNumber: '8',
    neighborhood: 'Centro',
    city: 'Madrid',
    postalCode: '28014',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4180,
    longitude: -3.7010,
    formattedAddress: 'Calle de Sevilla, 8, 28014 Madrid',
  },
  {
    id: 'addr-se-3',
    streetName: 'Calle del Sena',
    neighborhood: 'Chamberí',
    city: 'Madrid',
    postalCode: '28010',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4350,
    longitude: -3.6950,
    formattedAddress: 'Calle del Sena, 28010 Madrid',
  },
  {
    id: 'addr-se-4',
    streetName: 'Calle de Sebastián Elcano',
    streetNumber: '34',
    neighborhood: 'Arganzuela',
    city: 'Madrid',
    postalCode: '28045',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4010,
    longitude: -3.6970,
    formattedAddress: 'Calle de Sebastián Elcano, 34, 28045 Madrid',
  },
  {
    id: 'addr-se-5',
    streetName: 'Avenida del Señorío de Illescas',
    streetNumber: '56',
    neighborhood: 'Carabanchel',
    city: 'Madrid',
    postalCode: '28044',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.3850,
    longitude: -3.7450,
    formattedAddress: 'Avenida del Señorío de Illescas, 56, 28044 Madrid',
  },
  {
    id: 'addr-se-6',
    streetName: 'Calle del Serpiente',
    streetNumber: '3',
    neighborhood: 'Malasaña',
    city: 'Madrid',
    postalCode: '28004',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4280,
    longitude: -3.7080,
    formattedAddress: 'Calle del Serpiente, 3, 28004 Madrid',
  },
  {
    id: 'addr-se-7',
    streetName: 'Paseo de la Senda del Rey',
    neighborhood: 'Moncloa-Aravaca',
    city: 'Madrid',
    postalCode: '28040',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4450,
    longitude: -3.7280,
    formattedAddress: 'Paseo de la Senda del Rey, 28040 Madrid',
  },
  {
    id: 'addr-se-8',
    streetName: 'Calle de Serrano Anguita',
    streetNumber: '21',
    neighborhood: 'Chamberí',
    city: 'Madrid',
    postalCode: '28004',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4310,
    longitude: -3.6990,
    formattedAddress: 'Calle de Serrano Anguita, 21, 28004 Madrid',
  },
  {
    id: 'addr-se-9',
    streetName: 'Calle de Serrano Jover',
    streetNumber: '7',
    neighborhood: 'Argüelles',
    city: 'Madrid',
    postalCode: '28015',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4340,
    longitude: -3.7150,
    formattedAddress: 'Calle de Serrano Jover, 7, 28015 Madrid',
  },
  {
    id: 'addr-se-10',
    streetName: 'Calle del Segundo Izquierdo',
    streetNumber: '15',
    neighborhood: 'Tetuán',
    city: 'Madrid',
    postalCode: '28020',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4580,
    longitude: -3.7020,
    formattedAddress: 'Calle del Segundo Izquierdo, 15, 28020 Madrid',
  },
  {
    id: 'addr-se-11',
    streetName: 'Calle de la Serenidad',
    streetNumber: '42',
    neighborhood: 'Hortaleza',
    city: 'Madrid',
    postalCode: '28033',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4720,
    longitude: -3.6580,
    formattedAddress: 'Calle de la Serenidad, 42, 28033 Madrid',
  },
  {
    id: 'addr-se-12',
    streetName: 'Avenida de Séneca',
    streetNumber: '88',
    neighborhood: 'Ciudad Universitaria',
    city: 'Madrid',
    postalCode: '28040',
    province: 'Madrid',
    country: 'Spain',
    latitude: 40.4510,
    longitude: -3.7320,
    formattedAddress: 'Avenida de Séneca, 88, 28040 Madrid',
  },
  // Barcelona addresses
  {
    id: 'addr-6',
    streetName: 'Passeig de Gràcia',
    streetNumber: '92',
    neighborhood: 'Eixample',
    city: 'Barcelona',
    postalCode: '08008',
    province: 'Barcelona',
    country: 'Spain',
    latitude: 41.3950,
    longitude: 2.1640,
    formattedAddress: 'Passeig de Gràcia, 92, 08008 Barcelona',
  },
  {
    id: 'addr-7',
    streetName: 'La Rambla',
    neighborhood: 'Ciutat Vella',
    city: 'Barcelona',
    postalCode: '08002',
    province: 'Barcelona',
    country: 'Spain',
    latitude: 41.3800,
    longitude: 2.1730,
    formattedAddress: 'La Rambla, 08002 Barcelona',
  },
  {
    id: 'addr-8',
    streetName: 'Avinguda Diagonal',
    streetNumber: '456',
    neighborhood: 'Les Corts',
    city: 'Barcelona',
    postalCode: '08029',
    province: 'Barcelona',
    country: 'Spain',
    latitude: 41.3890,
    longitude: 2.1350,
    formattedAddress: 'Avinguda Diagonal, 456, 08029 Barcelona',
  },
  // Valencia addresses
  {
    id: 'addr-9',
    streetName: 'Calle Colón',
    streetNumber: '15',
    neighborhood: 'Eixample',
    city: 'Valencia',
    postalCode: '46004',
    province: 'Valencia',
    country: 'Spain',
    latitude: 39.4700,
    longitude: -0.3760,
    formattedAddress: 'Calle Colón, 15, 46004 Valencia',
  },
  {
    id: 'addr-10',
    streetName: 'Avenida del Puerto',
    neighborhood: 'Poblats Marítims',
    city: 'Valencia',
    postalCode: '46023',
    province: 'Valencia',
    country: 'Spain',
    latitude: 39.4550,
    longitude: -0.3300,
    formattedAddress: 'Avenida del Puerto, 46023 Valencia',
  },
  // Sevilla addresses
  {
    id: 'addr-11',
    streetName: 'Avenida de la Constitución',
    streetNumber: '28',
    neighborhood: 'Casco Antiguo',
    city: 'Sevilla',
    postalCode: '41001',
    province: 'Sevilla',
    country: 'Spain',
    latitude: 37.3860,
    longitude: -5.9940,
    formattedAddress: 'Avenida de la Constitución, 28, 41001 Sevilla',
  },
  {
    id: 'addr-12',
    streetName: 'Calle Sierpes',
    neighborhood: 'Casco Antiguo',
    city: 'Sevilla',
    postalCode: '41004',
    province: 'Sevilla',
    country: 'Spain',
    latitude: 37.3900,
    longitude: -5.9960,
    formattedAddress: 'Calle Sierpes, 41004 Sevilla',
  },
  // Additional Sevilla addresses with "Se"
  {
    id: 'addr-se-sev-1',
    streetName: 'Calleセルジオ Carmona',
    streetNumber: '18',
    neighborhood: 'Triana',
    city: 'Sevilla',
    postalCode: '41010',
    province: 'Sevilla',
    country: 'Spain',
    latitude: 37.3820,
    longitude: -6.0050,
    formattedAddress: 'Calle Sergio Carmona, 18, 41010 Sevilla',
  },
  {
    id: 'addr-se-sev-2',
    streetName: 'Calle Secretario',
    streetNumber: '5',
    neighborhood: 'Macarena',
    city: 'Sevilla',
    postalCode: '41009',
    province: 'Sevilla',
    country: 'Spain',
    latitude: 37.4010,
    longitude: -5.9880,
    formattedAddress: 'Calle Secretario, 5, 41009 Sevilla',
  },
  // Málaga addresses
  {
    id: 'addr-13',
    streetName: 'Calle Larios',
    streetNumber: '5',
    neighborhood: 'Centro Histórico',
    city: 'Málaga',
    postalCode: '29005',
    province: 'Málaga',
    country: 'Spain',
    latitude: 36.7210,
    longitude: -4.4220,
    formattedAddress: 'Calle Larios, 5, 29005 Málaga',
  },
  {
    id: 'addr-14',
    streetName: 'Paseo Marítimo Pablo Ruiz Picasso',
    neighborhood: 'La Malagueta',
    city: 'Málaga',
    postalCode: '29016',
    province: 'Málaga',
    country: 'Spain',
    latitude: 36.7150,
    longitude: -4.4050,
    formattedAddress: 'Paseo Marítimo Pablo Ruiz Picasso, 29016 Málaga',
  },
];

// Search mock addresses based on query
export function searchAddresses(query: string): MockAddress[] {
  if (!query || query.length < 2) return [];
  
  const lowerQuery = query.toLowerCase();
  return mockSpainAddresses.filter(
    (addr) =>
      addr.streetName.toLowerCase().includes(lowerQuery) ||
      addr.neighborhood.toLowerCase().includes(lowerQuery) ||
      addr.city.toLowerCase().includes(lowerQuery) ||
      addr.formattedAddress.toLowerCase().includes(lowerQuery)
  );
}
